services:
    sargointern:
        command: ["pnpm", "start", "--character=./characters/sargointern.character.json"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        env_file:
            - .env.production
        ports:
            - "3000:3000"
        restart: always
